- hosts: web
  tasks: 
   - name: copy file
     copy: 
      src: copy.html
      dest: /var/www/html/index.html
   - name: service restart
     service: 
      name: nginx
      state: stopped
      
